version: "3.7"

services: 
  server:
    build: ./server 
    container_name: server_
    ports: 
      - "50051:50051"

  client:
    build: ./client
    container_name: client_
  redis:
    image: redis:6.0.5
    ports: 
      - "6379:6379"
    command: redis-server
